### ISSUE TITLE
Migrate to github actions for releasing packages

### ISSUE THREAD

**Issue by apuntovanini** [uidu-org/guidu#72]
Travis will be soon moved over to travis.com, so we should move build scripts to github actions

**Comment by apuntovanini** [comment]
Nice first task 👯 
Not an easy one, happy to help you out anytime

**Comment by volivers** [comment]
I'll dive deeper into it once my setup is complete. Thanks!

**Comment by apuntovanini** [comment]
May help: https://github.com/actions/virtual-environments/issues/4

**Comment by volivers** [comment]
Thanks! I'll review that issue asap.
--
Also tried downgrading to Node 10, but it fails on Travis' end.
And added a matrix strategy to the setup-node which also didn't work.

**Comment by apuntovanini** [comment]
Indeed seems to work!
